name: Run TestComplete Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run TestComplete Project
      run: |
        & '"C:\Program Files (x86)\SmartBear\TestComplete 15\Bin\TestComplete.exe"' `
        '"C:\Users\nicholas.dimartino\AppData\Local\Jenkins\.jenkins\workspace\QMetry - Nicky Ds Sammies and Subs Integrations\ProjectSuite1\ProjectSuite1\Nicky Ds Sammies and Subs.pjs"' /run /exit /SilentMode /ErrorLog
